### ISSUE TITLE
[Patch] fixed de.yml

### ISSUE THREAD

**Issue by projectplant** [Coren/redmine_advanced_roadmap_v2#38]
Hi,
I fixed the mistakes in the german language file. Please feel free to use it.
Regards,
Marc.

```
de:
  label_click_to_enlarge_reduce: "Klicken zum Vergrößern/Verkleinern"
  label_estimated_speed: "Geschätzte Geschwindigkeit"
  label_f_day: "%{value} Tag"
  label_f_day_plural: "%{value} Tage"
  label_f_week: "%{value} Woche"
  label_f_week_plural: "%{value} Wochen"
  label_milestone: "Meilenstein"
  label_milestone_new: "Neuer Meilenstein"
  label_milestone_plural: "Meilensteine"
  label_setting_show_due_time: "Zeige die verbleibende Zeit anstatt der Fälligkeit"
  label_setting_color_bad: "Farbe für schlechtes Drehzahlverhältnis"
  label_setting_color_good: "Farbe für gutes Drehzahlverhältnis"
  label_setting_color_very_bad: "Farbe für sehr schlechtes Drehzahlverhältnis"
  label_setting_ratio_bad: "Schlechtes Drehzahlverhältnis"
  label_setting_ratio_good: "Gutes Drehzahlverhältnis"
  label_setting_ratio_very_bad: "Sehr schlechtes Drehzahlverhältnis"
  label_setting_solved_issues_to_estimate: "Gelöste Tickets zu schätzen"
  notice_unable_delete_milestone: "Meilenstein konnte nicht entfernt werden."
  permission_manage_milestones: "Meilensteine verwalten"
  permission_view_issue_estimated_hours: "Ansicht veranschlagte Stunden"
```
